server:
  port: 8081

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Maserati_car?serverTimezone=GMT%2b8
    username: root
    password: 426218107liuf

  mail:
    host: smtp.163.com
    username: swords_man12@163.com
    password: GREGATUSDHBSFYIA

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8

  data:
    elasticsearch:
      cluster-name: elasticsearch   #集群的名字
      cluster-nodes: 127.0.0.1:9300

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /



#配置mybatis
mybatis:
  type-aliases-package: com.heng.org.domain,com.heng.org.query,
                        com.heng.auth.domain,com.heng.auth.query,
                        com.heng.sys.domain,com.heng.sys.query,
                        com.heng.car.domain,com.heng.car.query,
                        com.heng.user.domain,com.heng.user.query,
                        com.heng.shop.domain,com.heng.shop.query,

  #别名包的配置
  #扫描mapper.xml文件,当mapper.xml和Mapper.java接口在同一个包下时，可以不配置
#  mapper-locations: classpath:com/heng/*/mapper/*Mapper.xml

permission:
  scan-base-package: com.heng.org.controller,com.heng.auth.controller

fastDfs:
  prefixUrl: "http://115.159.217.249:8888"

jarvis:
  verificationCodeExpiration:
    timeout: 3
  carDetail:
    htmlPath: /Users/jarvis/Java/Idea/car-platform-client/cardetail
  messageCodeExpiration:
    timeout: 5
