#数据库的链接配置
spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swords_man-crm?serverTimezone=UTC
    username: root
    password: 426218107liuf



#配置mybatis
mybatis:
  type-aliases-package: com.heng.org.domain,com.heng.auth.domain,com.heng.test.domain,com.heng.test.query

#别名包的配置
  #扫描mapper.xml文件,当mapper.xml和Mapper.java接口在同一个包下时，可以不配置
#  mapper-locations: classpath:com/heng/*/mapper/*Mapper.xml

permission:
  scan-base-package: com.heng.org.controller,com.heng.auth.controller


